### ISSUE TITLE
[Issue] Regionerator not working

### ISSUE THREAD

**Issue by DanyardTheWolf** [Jikoo/Regionerator#10]
Hey, so i recently tried out regionerator. and it appears to not be working. it's red in the plugins list and it won't work. 

I'm on PaperMC 1.14.4

**Comment by Jikoo** [comment]
Startup logs? Regionerator version? Need more information.

**Comment by DanyardTheWolf** [comment]
I'm on v1.5.6 and it's getting errors when trying to enable itself. can't even hook to lands.
![Merknad 2019-08-20 160013](https://user-images.githubusercontent.com/29733625/63353829-9fb30900-c363-11e9-8345-37449affcd15.png)

**Comment by Jikoo** [comment]
Ah, Lands, thanks. Apparently the API has undergone a lot of changes. I'll be looking into it soon.

The reason I needed more info is because I don't run most of the plugins Regionerator hooks myself and it's not worth attempting to monitor changelogs for the various plugins - premium plugins have a nasty habit of pushing out excessively frequent tiny updates to bump themselves in the plugin listing.

**Comment by DanyardTheWolf** [comment]
No problem. and btw i'm using papermc. hope i helped :)

**Comment by Jikoo** [comment]
[1.5.7](https://github.com/Jikoo/Regionerator/releases/tag/1.5.7) should address this. Unfortunately Lands doesn't load all protections like other plugins, so database response time will affect checks. The only main thread check SHOULD be if `/regionerator check` is used, but frankly I should think about rewriting Regionerator anyway.
