### ISSUE TITLE
Design spec for improved Minecraft region regeneration.

### ISSUE THREAD

**Issue by TomLewis** [Jikoo/Regionerator#111]
I just found this plugin by looking at your github after replying about siege! and nearly exploded as I have been looking for somone to update the [Regenerator plugin](https://www.spigotmc.org/resources/regenerator.23409/) I found when I moved from 1.12.2 to 1.18.1, as you most likley can tell having a 9 year old world that we genreated in 1.7.10 is in need of a fresh clean!

Im not sure if you made this from scratch or is a fork of the regenerator plugin, but I would like to explain my situation and see if this plugin could be used.

My map: https://map.piratemc.com you can see where the new 1.18 world expansion has happened, and you can see the old beaten up world!

The problem with old worlds is every chunk is marked as "visited", check out this amazing visual, Dynmap has an Inhabited render that works off the exact chunk data of "visited" so it creates a heatmap of whats been used:

![Screenshot 2021-10-28 19 24 32](https://user-images.githubusercontent.com/144046/153199249-54b415bf-5fa6-49cc-ae96-ec2606e79df0.png)

So what would happen here, is nothing, all these chunks as they have been visited so many times would never get regenerated!

Since im not sure if this plugin is supported, if its a fork or what, im going to just spitball some ideas just incase!

1. Manual Region regen command - Possability for players & staff to request an area be regenerated.
    1. Each region/chunk can only be checked every X time to see if it can be regenerated, this would most likley require some sort of database to track, this solves players trying to regen all the time for free ores, but it also solves not requiring a need for staff to get involved.
    2. The check has to check if any griefprevention claims/WG are in that region, if there are it fails! The user would be required to remove/get staff to remove any claim, even their own claims first!
    3. Users get X amount of regions to mark for regen.
    4. Regions that havent been regenerated in X time and dont have claims get put into "pending" and not done stragiht away (See following points)
2. Backup region to folder, when a region gets deleted, for the sake of sanity, copy/paste the region file to a backup folder first, then we can always copy it back and restart if shit hits the fan!
3. Dynmap intergration. This is the meat of it all! Each region can be a color coded square on the live map! When a region is marked as pending it has X time before its automatically deleted, this gives players & staff time to visit and check it over before its wiped! it could be as simple as, if a player does not want that region regneerated they need to make a claim X size in the region so when the timer is up, it gets re-checked for claims and blocks the regen/marks it on the map as blocked.
    1. Green squared could be "recently regenerated" and have a timer for when it can next be regenerated, so if its set at 1 year until that region can be regenerated, itll say 1 year when clicked
    2. Orange/yellow could mean pending (traffic light system here!) 
    3. Red = failed for: click to see reason.
4. Allow Staff to blacklist regons for regen to prevent peolpe even trying to regen it (markets, spawn, warps etc)
5. Auto-checking regions, like dynmap has its command to renderall, this could work similar and check over every region one by one and check if it has Claims in it, then they could be auto marked as pending (if wanted) or there could be a force remove from this command too, so this could be used on a test server first to trial what a full world clean would look like. Good for debugging too.
6. Allow the manual command to have a parameter for region names, so it can be used by console, this then allows external plugins to trigger a manual regen into pending or instnat removal. Then differnt triggers/events could be used to cleanup a region.

If I think of any other parameters that may cause issue I will update the main list!

**Comment by Jikoo** [comment]
> Those points I wrote out were a design spec to how how a region cleaner should work with the most control, involving players and being able to check with backups when it does a destructive task, not asking if it already does it.
> 
> Looks like you're not interested in upgrading this plugin, no problem..

> Its a design spec to fix a flaw not asking how yours currently works.

Excuse me, what? Your "upgrades" are purely the system you want, not what Regionerator is, and it's incredibly offensive to come here and suggest that I've written a plugin that is flawed because it doesn't function to some arbitrary other specification. You're not paying me, feel free to not use the plugin that I wrote that doesn't suit your needs instead of telling me it sucks. In fact, that seems like exactly what you did [last time you were here](https://github.com/Jikoo/Regionerator/discussions/61).

Regionerator is designed to minimize staff load, not require it. Player input is not desired.

I agree that backups would be a nice feature, but I never felt the need because there are other plugins that already do backups with incredibly detailed configuration options.

> Few thoughts:
> 
> > In general my problem with Dynmap integration is that Dynmap tends to load chunks. Loading chunks causes the server to override Regionerator unless it happens after the fact.
> 
> I think you miss-understood, I'm talking about drawing rectangles on the live map, nothing in-game, its just drawing a DIV on the webpage.

Generally when Dynmap re-draws anything in a tile it re-draws the tile. That may have changed in the years since I last touched Dynmap, but I'm generally disinterested in it (and the ensuing need to support BlueMap and Pl3xMap).

Regionerator also operates on a per-chunk basis, not the per-region basis it originally did, which seems like a horrible amount of visual clutter.

> This is the problem that I explained in the original post "potentially active" you are reading this information from chunks correct? Thats the first part of my post explaining why its flawed for old worlds, and Im showing the inhabited map to show you that every single chunk in an old world is "inhabited/visited/active" whatever you want to call it, its flawed method of measuring, its why I designed a better one with a database backend.

I don't think you understood. The only thing Regionerator pulls from MC chunks is **last modification time**. What you are looking at is **inhabited time**. Those are very different things. Regionerator does not care if a player has lived in the chunk for a quarter century, if it's unprotected and has not been logged as visited within the specified duration Regionerator is going to attempt to delete the chunk.

**Comment by TomLewis** [comment]
Sorry, I think you have missunderstood, this isnt a demand or request at all, no need to get agressive.

This is why I said to _not worry about it_ when I saw your first reply, I understood you do not want to add features to this plugin, its fine. No worries.

This was **only** a design spec for an upgraded/player & staff focosed/safer regenerator plugin that Ive had in mind and thought I would share my idea with you, thats all mate.

Dont worry about it, Im only giving ideas for how to improve & expand the scope of a regenrator for everyone.

> Regionerator is designed to minimize staff load, not require it. Player input is not desired.

Yup, same as the spec I laid out, except mine is safer and gives players/staff time to check over a region first.

**Comment by Jikoo** [comment]
> You need to learn to read tone.

You need to learn to express yourself in a way that doesn't involve taking shots every other sentence.

> Its a design spec to fix a flaw not asking how yours currently works.

How would you interpret this? Personally, this says to me "I don't care what your plugin is actually intended to do, it doesn't do what I want and therefore it is flawed."

> Looks like you're not interested in upgrading this plugin, no problem..

How this is not a passive-aggressive jab at both me and this plugin? "Gee, I'm sorry you're so close-minded that you won't fix your plugin by entirely rewriting it to have my superior feature set."

I'm open to adding features. I'm not open to rewriting the core thing Regionerator is designed to do. I'm not open to letting people walk all over me and my work because they don't like what my plugin does.

> Just wasted my time writing it up

At least now you have it all in one place so you can easily request it of someone else with a copy and paste.

<hr>

> > Regionerator is designed to minimize staff load, not require it. Player input is not desired.
> 
> Yup, same as the spec I laid out, except mine is safer and gives players/staff time to check over a region first.

Your idea is focused heavily on spending a lot of time reviewing what the plugin is doing. Regionerator is designed to be a hands-off automatic approach, set and forget. I appreciate the detail of your specifications - they seem nice, they're just not close to what Regionerator is trying to do. This does not indicate an issue with Regionerator, it just means that Regionerator, while it has some similar functions to the plugin you want, is not the plugin you want.

Someone could "relatively easily" throw that deletion mode on top of Regionerator by disabling its inbuilt deletion and leveraging its player tracking and region reading/writing systems, but the core feature set is so different that they may as well just write a whole new plugin. I have already written my own ideal deletion plugin, so that's not a project I personally am willing to take on - programming is a fun hobby for me, I only really do passion projects these days.

> The reason people don't use bluemap on SMP is because players can find ways to break into bases and snoop around much easier.

Fair, wouldn't really know.

> Per chunk wouldn't work for the live map as it would be an insnae amount of clutter, that's why I said region, maybe you should rename this plugin to explain what it now does? I suggest "Chunk Regenerator".

Plugins evolve. Regionerator still refreshes regions, it just also refreshes them by orphaning individual chunks in addition to deleting them wholesale. Pretty much every page in the wiki talks about per-chunk features. The configuration also contains chunk-based settings. Maybe I should add a FAQ entry "What is Regionerator" though, that's a good idea.

Honnestly I wish I'd never released this to the public at all. I did because WorldBeautifier did exactly what I needed and nothing filled the niche after it got deleted off Spigot - figured I'd share my solution with my fellow abandoned Spigoteers - but once I stopped helping administrate servers it quickly became one of my least favorite projects. It's always felt like it has demanded the most time and effort from me.

I feel that it's unfair to include the first half of my post and not give you the option of a reply so I'm not going to lock the conversation, but I'm hoping you'll just leave it here. I'll see you around on other issue trackers, best of luck with refreshing your world.

**Comment by TomLewis** [comment]
> Afaik if you delete an entire region MC's internal blending system will create blended border chunks on that region. 
Sounds like something that I could test and see what happens, when I expanded the world it somehow automatically did it without any input from me.

> A //regen etc. is different because WE internally generates that area in a separate new world. 

Yup. We have been using //regen for 9+ years as our way of cleaning up a world manually, sadly since moving from 1.12.2 to 1.18.1 theres quite a dramatic change with terrain which is why im exploring methods of queueing up regions that can be cleared. 

They are just region files at the end of the day, so maybe its as simple as generating a list of all region names for all claims & wg claims, and then I can remove that from the list of region names and I have a list of all regions without claims no need for a plugin overhead.

Ill figure it out, or find someone thats up for the challange 👍

**Comment by TomLewis** [comment]
Im not sure if you care for an update, but I will share it anyway just incase.

I tested manually deleting a region in the middle of the 1.12 world, and it seems to have generated new 1.18 terrain but at a lower level automatically blending in, so the generator does work this way.

So there are technically 3 types of terrain now, anything pre 1.18 (1.12 in my case), 1.18 terrain and then this hybred blend.

![Screenshot 2022-02-24 at 12 14 50](https://user-images.githubusercontent.com/144046/155522600-5c78a1a1-084f-4ab6-968d-947b1a66e31e.png)

**Comment by Jikoo** [comment]
Excellent! I've heard that it does work that way, but confirmation is nice.
