### ISSUE TITLE
Feature request: check if chunk is void hook

### ISSUE THREAD

**Issue by Leonardo-DGS** [Jikoo/Regionerator#12]
Adding an hook to check if the chunk is completely void will be useful for SkyBlock servers and will support all SkyBlock plugins.

**Comment by Jikoo** [comment]
Just write a script that deletes region files under a certain size when your server restarts.

To support this Regionerator would need to take a completely different approach to deletion.

Regarding individual chunks: Regionerator doesn't actively remove data from region files, it wipes chunk pointers so the region assumes the area the chunk was saved in is dead space and eventually cleans it out. An all-air chunk is so small in terms of storage that you are unlikely to notice any difference when individual chunks are abandoned.

Additionally, to actually check if a chunk is empty I'd either have to parse it myself (a lot of effort and extra resource usage that is unnecessary) or load the chunk which would then save, wiping region file modifications. Regionerator really isn't designed to aggressively delete area because that's a waste of time. Stuff that's in use is only going to be generated again, and world generation is costly. As such, it's counterproductive to prevent saving when deleting, as stuff that's saved is likely relevant.

**Comment by Jikoo** [comment]
If you have any more questions or want to discuss this further please use an existing issue instead of a new one.
