### ISSUE TITLE
Delete entity/POI data with regions

### ISSUE THREAD

**Issue by Folas1337** [Jikoo/Regionerator#156]
From what I've seen it seems that when chunks are deleted and regenerated, the old entities stay and new ones that generate with a chunk inevitably (such as villagers, drowned, pigs, sheep etc) are just added on top, often leading to big areas of mobs basically stacked over each other.

If that assumption is correct, could we get an option that would let Regionerator also delete entities in chunks it deletes?

**Comment by Jikoo** [comment]
Entities are stored in chunks. Regionerator deletes chunks, which means Regionerator also deletes the entities stored in those chunks. If Regionerator were somehow failing, one assumes abandoned base sites would be littered in armor stands, item frames, and paintings.

What you're likely seeing is that entities spawn in clumps of 1-4 during chunk generation. All are the same type and variant of entity and all are on the same block. You would never see this during normal early game exploration because the entities would move and then shove each other away before you got close.
This may be an inconsistency/optimization over vanilla behavior in Spigot, but it has nothing to do with Regionerator.

**Comment by Folas1337** [comment]
OK, thanks for clarifying so quickly, I guess it's just me imagining things or whatever it might be.

I just thought that ./world/entities stored the entities and not ./world/region but I assume you know what you're talking about and that the entities are deleted along with the chunks/regions :)

Cheers

**Comment by Jikoo** [comment]
I could well be wrong, but the only other person with similar concerns posted pictures that looked like ordinary post-gen plains screenshots. Without a change in chunk formats or definitively abnormal proof (i.e. an armor stand surviving the base it was in being deleted), it's much more likely that you're just seeing spawning from a perspective you wouldn't ordinarily have, i.e. teleportation or flight, and it looks weird.

To my understanding:
A nonexistent region results in everything else being deleted when the server attempts to load the region. Existing POI and entity data are not loaded and subsequently overwritten.
A nonexistent chunk is generated using existing POI data. Existing entity data is not loaded and subsequently overwritten.

This could be a good way to optimize disk usage further, but it would also be a performance hit.

**Comment by Jikoo** [comment]
I guess the best compromise here would be delete POI and entity data when whole regions are deleted.

POI data I have no interest in dealing with due to the fact that it must actually be parsed completely and very selectively edited based on which POIs are present and what chunks they cover. My goal with Regionerator has always been to handle deletion without version-specific code, and the more details need to be determined, the more Regionerator locks itself in to a single MC version.

Entity data presumably follows the .mca format to some degree and can be "cleared" without too much work. However, this would double disk I/O for what is essentially just peace of mind.

**Comment by Folas1337** [comment]
I mean what you are saying all makes sense, I am not doubting you or anything but from what I've seen, chunks that have been visited before get a lot more mobs than what I normally see in newly generated chunks.

The further I go from spawn, the more normal it gets and the closer I get to areas that I know have been visited before but have been deleted again, it starts looking suspicious. I'll gather a couple images to compare them and leave them here. Thanks for showing any interest in this at all, even if it might be another couple weeks, months or however long it might be for this to get implemented at all :D

**Comment by Folas1337** [comment]
This is the kind of spawning I'm used to seeing in new chunks:
![image](https://user-images.githubusercontent.com/39222968/221305189-002607b1-ab6f-4297-aa70-2db8b1f8bac0.png)
Maybe a bit of a bigger group like this:
![image](https://user-images.githubusercontent.com/39222968/221305248-de48b407-ebc2-4eae-ac60-37185a629690.png)

But I think this is one where you can see the problem quite clearly, rabbits and donkeys in these large groups I am seeing nowhere when I'm flying out in new areas:
![image](https://user-images.githubusercontent.com/39222968/221305075-6a8b3837-fb52-4541-86b1-f170d32aea17.png)
Using `/execute if entity @e[type=minecraft:rabbit,distance=..50]` in that area yielded a count of 42, slightly too many in my opinion and I have no other explanation of why this is happening other than when chunks are generated.

Too many sheep in this one:
![image](https://user-images.githubusercontent.com/39222968/221306216-33cf2bb6-f31c-4348-a931-86360b54b999.png)
I mean...:
![image](https://user-images.githubusercontent.com/39222968/221306526-5f227414-f827-4e83-9f5e-d73cdfe9ad96.png)

And I've seen the same with drowned, all of these mobs generate on chunk generation and for monsters this never happens, although to be fair for monsters it could also be due to despawning being handled differenty.

I hope this shows well enough what I see as a problem.

**Comment by Jikoo** [comment]
Re: other plugins - really depends on how they handle data. Prior to writing this plugin, I never thought about the ramifications of chunk gen for my data. You "can't" delete area in Minecraft, and anyone who does probably deleted their whole world and my stored data too. I now make sure to overwrite or delete my own data for chunks when they generate, but I wouldn't be surprised to hear someone wasn't doing that. It's reasonable not to expect something that doesn't happen in vanilla.

As far as this goes, those entity counts are highly improbable for natural generation. It's not as definitive as something like an armor stand or a named entity, but it does seem likely that Minecraft is no longer clobbering entity data when chunks do not exist.

The major rough part on my end trying to support entities is that no one I'm aware of has documentation on the format. While I suspect that entity .mca files have an identical header system and store a list of entity NBT tags per chunk, figuring out if that's true is still going to require a lot of reading and testing.

**Comment by Folas1337** [comment]
If I can be of any help without programming/coding involved, let me know, I'd be willing to support you on this matter :)

**Comment by Jikoo** [comment]
The change itself isn't too complex, I've already got a basic messy version in 9c93361fa583225379a7674ba0d52b51f2a9dff5. What I really need is confirmation that .mca files are Mojang's generic per-chunk data format, and I've been unable to find any information or tools that confirm either way in my searches. The only editing tools I could find that do support entities are very dated.

At this point, there are two options:
1) Dive into MC and interpret the classes that actually handle reading/writing .mca files
2) Adapt existing code for parsing .mca files to dump the uncompressed NBT instead of interpreting it into specific structures

I'm reasonably confident that option 2 would actually work (and would probably offer an opportunity to dust off my Python) but we'll see how lazy I end up being.

**Comment by Jikoo** [comment]
Turns out the first and second options are basically the same thing because Mojang posted the source for the original official .mca handling code: https://pastebin.com/niWTqLvk
It's changed a little since then, but yes, region files are just per-chunk data dumps that may be anything.

This is extra good because I was entirely unaware of or completely forgot about .mcc files for oversized chunks.

**Comment by Folas1337** [comment]
> Turns out the first and second options are basically the same thing because Mojang posted the source for the original official .mca handling code: https://pastebin.com/niWTqLvk
> It's changed a little since then, but yes, region files are just per-chunk data dumps that may be anything.
> 
> This is extra good because I was entirely unaware of or completely forgot about .mcc files for oversized chunks.

I'm not entirely sure how to translate that to something I understand. Mainly "which parts is Regionerator taking care of?", "What's the difference between mca and mcc?", "what are oversized chunks" but also what does that mean in the grand scheme of Regionerator?

**Comment by Jikoo** [comment]
> Mainly "which parts is Regionerator taking care of?"

Currently Regionerator just handles deleting chunk data. In prior versions, MC handled the rest of the cleanup when the region was loaded or the chunk was generated.

> "What's the difference between mca and mcc?"

.mca is MC's primary region file format:
All data is stored in 4096 byte sectors. Files are required to have a size that is a multiple of 4096 bytes.
The header is 8192 bytes containing sector addresses for relative chunk locations' data followed by the last modification of that data.
The relative locations' data is a bit more of a mess to explain, but essentially it starts with 4 bytes containing a more precise data length, then the compression type, and then the compressed data.

> "what are oversized chunks" 

Due to the fact that the data length is stored in 4 bytes, if the actual length of the compressed data exceeds a 4 byte number, it cannot be stored in a .mca file. In this case, the data is dumped into a .mcc file `c.<non-relative chunk X>.<non-relative chunk Y>.mcc`.
In older versions data exceeding the save length actually just resulted in the chunk being deleted, which was a source of a chunk deletion exploit usually tied to the numerous exploits around massive NBT tags in writable books. Drop a massive book on the ground or plop it into a container, voila, chunk was deleted when it tried to save.

> but also what does that mean in the grand scheme of Regionerator?

This means that Regionerator will need to update to support MC not clobbering entities when it generates a chunk, but Regionerator is capable of handling entities identically to chunks. The data stored is of different types, but the format is the same. It's extra confusing because we refer to everything as being stored "by chunk" when technically it's "by chunk location relative to the region's coordinates"

9c93361fa583225379a7674ba0d52b51f2a9dff5 should be functional but I would like to clean it up some before I do a full release. In particular, I need to revisit and optimize disk operations. Regionerator's usage of RandomAccessFile is way more optimized than average, but tripling our disk usage makes its performance 3 times worse than it was. I don't think that's a huge dealbreaker (the hooks that aren't async-capable are a thousand times worse for speed) but I don't want to push out a fix of this nature without investigating further improvements. The less time we spend writing, the less time there is for inconsistencies with MC.

Regionerator also needs to support deleting relevant .mcc files. While they won't be loaded into the game once the region has been edited to orphan them, they also will not be deleted... and a single .mcc file is at a minimum 1MB, which roughly the same size as about 200 normal chunks, 1/5 of an average region.

**Comment by Folas1337** [comment]
Hey, hey, hey, checking in with my favorite developer :) Hope you're doing great!
Just wondering how progress on this whole thing is as I'm curious and also today I came to realize that even when you use this plugin for a dimension like the end, it won't regenerate elytras cause they only spawn in item frames and item frames are entities which aren't regenerated currently, quite funny and keeps them as rare as they are (although not exactly the outcome I wanted but it is what it is).

**Comment by Jikoo** [comment]
I started in and got burned out again like an absolute champion. I did get through testing the internal deletion technique and it did appear that the deletion runnable was working based on limited runs with doctored data on known regions, but I'm always really leery of cutting releases after changes to deletion.

Re: end ships: honestly a bit surprised that wouldn't just duplicate the item frame. Maybe the structure placement logic loads entities and says, "Oh, an item frame is here already, we're good."

**Comment by ChiboYen** [comment]
Thanks Jikoo for all your effots towards making this plugin, our community appreciates your work sincerely. I have some evidence/screenshots of a few instances of chunk deletion not deleting the entities (end ships have a dropped item frame, and armor stands in place of where old bases were).

![image](https://github.com/Jikoo/Regionerator/assets/69435677/710813fb-0209-45af-951b-45b15056cad2)

I hope this provides the definitively abnormal proof you were looking for, we are on regionerator 2.3.0.

**Comment by Jikoo** [comment]
Builds are available via Appveyor, which only keeps them around for a month, so I've triggered a rebuild. Should be available in the artifacts tab when the run finishes here https://ci.appveyor.com/project/Jikoo/regionerator/builds/47422554
I haven't found anything noticeably wrong with it, but I also wasn't confident enough in it to push it to master because I know I made a couple basic (and bad) errors on the way to the current state.

**Comment by ChiboYen** [comment]
Unfortunately I am sad to say that something has gone terribly wrong in this build. Bases that were not supposed to be deleted have been deleted (our period is 4 months). Thankfully backups exist, but here's a screenshot of a base that was deleted's chunk/aftermath:

![image](https://github.com/Jikoo/Regionerator/assets/69435677/6c0ebf63-d3b8-4784-8659-29bb5a7c240e)

Here are some logs of the deletion as they were happening:
https://pastebin.com/ZtLQTg7X

**Comment by Jikoo** [comment]
Hmm, okay. The console error is me forgetting that there will be cases where the main region file or the entities file does not exist and blindly trying to read them. That should cause the region to be skipped, so the VisitStatus being orphaned is a separate problem. Did you happen to check any chunks before the cycle ran to see their VisitStatus, if it was correct prior to the cycle?

**Comment by ChiboYen** [comment]
Our server had the new experimental build implemented after a server reboot. The player's chunk/base in question above was online/present in the area and was even placing/breaking blocks, so the status should have been visited (no issue existed that would lead me to believe otherwise as this was still during the server on 2.3.0). Therefore, something in 2.5.0 is causing the flags to be incorrectly read (is orphaned even a state?) and chunks to be incorrectly deleted.

Unfortuantely, the deletion cycle happened right as the server rebooted with the correct version, there was no time before I could use /regionerator to check it.

**Comment by Jikoo** [comment]
No worries. Found the probable source, another simple (and terrible) mistake in the form of an inverted conditional. Also makes me wonder how I didn't notice that in my cursory testing. It reports anything existing on disk as orphaned, which then overrides the other visit statuses to prevent unnecessary database queries (if it's already orphaned on disk, it either has freshly generated and is still loaded, which will overwrite Regionerator's edits, or it is already deleted).
If you're still interested in testing, a new build is available: https://ci.appveyor.com/project/Jikoo/regionerator/builds/47431819/artifacts

**Comment by ChiboYen** [comment]
I'm glad to report the new build did not wipe any progress it seems at first glance (I will report back later after further testing). Thank you so much for the fix and all your efforts towards this free and wonderful plugin! I have a question however, on each deletion cycle does it scan the entire world? Below are some logs, which are a little concerning because of the massive amount of regions deleted:

```
[07:37:32] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 72840, deleted 42101 regions & 5293 chunks
[07:37:32] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 72860, deleted 42121 regions & 5293 chunks
[07:37:32] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 72880, deleted 42141 regions & 5293 chunks
[07:37:33] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 72900, deleted 42161 regions & 5293 chunks
[07:37:33] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 72920, deleted 42181 regions & 5293 chunks
[07:37:33] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 72940, deleted 42201 regions & 5293 chunks
[07:37:33] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 72960, deleted 42221 regions & 5293 chunks
[07:37:33] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 72980, deleted 42241 regions & 5293 chunks
[07:37:33] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 73000, deleted 42261 regions & 5293 chunks
[07:37:33] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 73020, deleted 42281 regions & 5293 chunks
[07:37:33] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 73040, deleted 42301 regions & 5293 chunks
[07:37:33] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 73060, deleted 42321 regions & 5293 chunks
[07:37:33] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] world: checked 73080, deleted 42341 regions & 5293 chunks
[07:37:33] [Craft Scheduler Thread - 162 - Regionerator/INFO]: [Regionerator] Regeneration cycle complete for world: checked 73082, deleted 42343 regions & 5293 chunks
```

Even though no one has reported anything improperly deleted (and we have backups, so no worries there), is this cause for concern? Could it just be that regionerator is deleting entities that were previously missed?

**Comment by Jikoo** [comment]
The whole world is checked every cycle, yes. You're right, the high count is likely artificially inflated by entity/POI data. I haven't changed the logging around those yet, if it's a region file it gets the region file handling. Definitely concerning compared to before due to the fact that the individual chunk count is so low, but if you have an unrestricted world that players previously explored a lot of, that wouldn't be terribly shocking - each person making a journey out 10k blocks would generate between 10 and 30 regions depending on direction assuming they didn't meander at all (so probably more), and if those were deleted by prior Regionerator runs, you'd be left with orphaned entity and possibly POI data for each.

**Comment by ChiboYen** [comment]
It's a 100K world border, practically unrestricted. I've just had the new build running for about a week with no major issues. I've double-checked my file count, it is roughly 30K, so the logging is accurate presumably. It doesn't appear to have deleted anything that shouldn't be deleted, so I would still believe it's orphaned entity data. Please let me know if I should be concerned othewise, thank you for the updates.

**Comment by Jikoo** [comment]
Okay, that does make more sense then. Means there were region files (potentially orphaned or otherwise) for nearly half the world, but if that makes sense to you, should be fine. Guess we're about ready to push towards a release.
