### ISSUE TITLE
ResidenceHook.java only checks for a Residence at Y=0

### ISSUE THREAD

**Issue by mb243** [Jikoo/Regionerator#2]
If the Residence does not extend all the way to bedrock, then the chunk does not appear to be claimed. See:

https://github.com/Jikoo/Regionerator/blob/master/src/main/java/com/github/jikoo/regionerator/hooks/ResidenceHook.java#L25

and 

https://github.com/Zrips/Residence/wiki/API

I've tested this on my own server. 

In order to properly detect a claim which doesn't extend all the way to bedrock, you would need to loop from Y=0 to Y=255 in this hook.

**Comment by mb243** [comment]
^ wrong reference, sorry :(

**Comment by mb243** [comment]
Looks like CoordinateConversions.chunkToBlock() is only returning a single block as well, which is causing incorrect results when checking claims.

**Comment by Jikoo** [comment]
>It also appears that CoordinateConversions.chunkToBlock() is only checking a single block within the chunk as well, which is causing incorrect results for '/rgr check'.

Pretty much all (sane) protection plugins organize their protections by chunk in some way, shape, or form.
Residence does as well, it just doesn't expose that, which I apparently blipped over when writing the hook.

Looks like pretty much all of the Residence API methods are hard hitters. Pretty terrible overall for a plugin of this nature. Even calling ResidenceManager#getFromAllResidences would not be a good idea - the method itself iterates over every single protection (not just the world in question's protection) and then I'd need to iterate over every protection calculating chunks contained until a match was found, if ever. Were Residence to use its own method for getting a world's claims, it could be a little more efficient, but it's not.

I think this issue is probably best addressed with an addition to Residence's API. It'd be quite easy to do, [the code already exists](https://github.com/Zrips/Residence/blob/21c92443d6e00b3c9ff93d7e5525d719620865d3/src/com/bekvon/bukkit/residence/protection/ResidenceManager.java#L67-L83). I'll open an issue later.

**Comment by mb243** [comment]
Thanks so much for looking into this :)

**Comment by Jikoo** [comment]
I'm still planning on writing up an issue requesting an API addition for Residence, but after some thought I really need to do some work on my end to support versioned hooks as well. As it is, the Factions hook is pretty ugly due to Factions and FactionsUUID support. It'll only get worse if I start supporting new methods and want to retain backwards compatibility - every hook has potential to be horrible looking.

**Comment by Jikoo** [comment]
Dang it, I did something stupid.

**Comment by mb243** [comment]
Still doesn't seem to be working right. Appears to return false all the time, even on claims that extend from bedrock to sky. 

Mind taking another look?

**Comment by Jikoo** [comment]
All right, I'm at a loss for why this isn't working correctly. Unless for some reason all areas count as sub-residences, there's no reason for them to not be detected. I guess we could try without that line, but otherwise the math appears to be fine.

**Comment by mb243** [comment]
Hmm. Okay, I'll re-enable it and double-check to see if I can get you any more info here. 

Happy to provide the server IP and some privileges if you'd like to take a peek for yourself. Let me know if you're interested.

**Comment by mb243** [comment]
Currently, no claims are being detected, even those extended to bedrock. I can't seem to compile the plugins as Maven complains of missing dependencies, but if you can add some debugging output, I'll be happy to test further.

**Comment by Jikoo** [comment]
Figured it out - ClaimedResidence#getWorld returns a String, not a World.

**Comment by mb243** [comment]
Works awesomely, and detects claims even if they don't extend down to bedrock. Thanks so much!

If you would like a coffee or three on me, let me know your PayPal email and I'll send you a little something.

Thanks again!

**Comment by mb243** [comment]
Closing this.

**Comment by Jikoo** [comment]
Glad to hear it's working. I'm always down for more coffee, thanks! adam.p.gunn at gmail.com
