### ISSUE TITLE
RAM usage and potential memory leak

### ISSUE THREAD

**Issue by ChiboYen** [Jikoo/Regionerator#65]
My server after an uptime of 23 hours with 15 GB of ram SWAP'd, meaning it had to use the page file since it ran out of memory. The cause of this after analyzing the heap dump was regionerator.

![image](https://ofsyad.wheres-my-ta.co/74H3by.png)
![image](https://ofsyad.wheres-my-ta.co/m5DUlH.png)
![image](https://ofsyad.wheres-my-ta.co/EDi5ul.png)
![image](https://ofsyad.wheres-my-ta.co/uLdd6o.png)

**Comment by Jikoo** [comment]
Edited your post to image link those, I don't click links I don't know.

**Comment by ChiboYen** [comment]
My apologies, the link domain is from sxcu.net (ShareX uploader)
Thank you for looking into the issue and responding so quickly

**Comment by Jikoo** [comment]
Exposed cache settings in fb3b6bb25ada28c519361802256c02c2fe9db44b.

New settings are explained in the [cache section of the config page](https://github.com/Jikoo/Regionerator/wiki/Configuration#cache). Note that since I didn't release a build since the previous changes config changes I didn't bump the config version, so if you did already update to a dev build the config won't have the new nodes added automatically.

Fair warning re: new config from before - I'm reasonably confident it works well, but I only lightly tested them.

The defaults have been changed so you may not need to do anything to hit whatever memory target you're shooting for with Regionerator. It'll always cap the cache during runs unless you have under cap chunks, but the queue should drain out a lot faster, so you should (ideally) see reduced memory usage when runs aren't active/recently completed.

**Comment by ChiboYen** [comment]
I'm not someone experienced in Java or even a developer, I just have a profiler for server performance analyzing purposes haha

Regardless, I've built the latest version of Regionerator, am I correct to assume its safe to upgrade by replacing the jar and deleting the old config to generate a new config? I've taken backups of the world as well

**Comment by Jikoo** [comment]
Oh, my bad, I should've told you builds are available [via AppVeyor](https://ci.appveyor.com/project/Jikoo/regionerator/build/artifacts). Yeah, you can delete the old config or just let it upgrade your existing one if you're running 2.2.1.

**Comment by ChiboYen** [comment]
Oh. My. God. Let me just say how amazing the new changes are! I installed the build on my production server (backup taken ofc) and it ran a complete cycle in about 3 minutes, where the old version would run extremely slow. We have a dedicated CPU (5600X) so cpu is not a problem, thank you for this update!

**Comment by Jikoo** [comment]
Config looks good.

Honestly as much as I wouldn't mind crediting the cache changes, those are pure memory/processing power balance. The cycle run speedup you're seeing probably is that the WG hook [wasn't declared async-capable](https://github.com/Jikoo/Regionerator/commit/294ab8eac0bf27f9c1e6f495ddb4f9f56135a757); sync hooks bog down the process horrendously. I really need to revisit the process to multithread visiting entire regions so that sync hooks can be used in larger batches, but that's a decent amount of complex work, so I've been putting it off.

Don't be too alarmed if you do see the max cache size exceeded by a bit when profiling - it's a soft cap that only gets enforced every  `minimum-expiration-frequency` seconds... which is a disclaimer I should have added to the wiki entry, whoops.
